version: "3"
services:
  python:
    build: .
    image: ml-base
    container_name: ml-base
    ports:
      - "9000:5000"
      - "9088:8888"  # Jupyter
      - "9082:8082"  # luigid
    volumes:
      - $PWD:/home/sandbox
      # - $HOME/.aws/credentials:/home/sandbox/.aws/credentials
    tty: true
