version: "3"
services:
  python:
    build: .
    image: python-ml
    container_name: ml
    # environment:
    #   - API_ENDPOINT_MECAB=http://52.196.5.52/api/v1/mecab
    #   - DEPLOY_ENV=dev
    ports:
      - "9000:5000"
      - "9088:8888"
    volumes:
      - $PWD:/home/sandbox
      - $PWD/docker/.jupyter/.jupyter:/.jupyter
      # - $HOME/.aws/credentials:/home/sandbox/.aws/credentials
    # command: /usr/sbin/init
    tty: true
